//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveManagementt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LeaveDetail
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "EmpID")]
        [Required(ErrorMessage = "EmpID is Required")]
        public int Employee_Id { get; set; }
        [Display(Name = "Leave Type")]
        public int? TypeOfLeave { get; set; }
        [Display(Name = "Leave description")]
        [Required]
        public string LeaveDescription { get; set; }
        public int LeaveStatus { get; set; }
        [Display(Name = "From Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        
        public System.DateTime FromDate { get; set; }
        [Display(Name = "To Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime ToDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Leave Leave { get; set; }
        public virtual Status Status { get; set; }
    }
}
