//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveManagementt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LeaveDetail
    {

        public int Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public int? TypeOfLeave { get; set; }
        public string LeaveDescription { get; set; }
        public Nullable<int> LeaveStatus { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{dd/MM/yyyy}", ApplyFormatInEditMode = true)]

        public Nullable<System.DateTime> FromDate { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{dd/MM/yyyy}", ApplyFormatInEditMode = true)]


        public Nullable<System.DateTime> ToDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Leave Leave { get; set; }
        public virtual Status Status { get; set; }
    }
}
